### ISSUE TITLE
Installation using go get

### ISSUE THREAD

**Issue by kvch** [laurent22/pmcctv#1]
First, thanks for the interesting project. :) I noticed a small thing in the Installation section. The command `go install github.com/laurent22/pmcctv` seems to be unecessary. According to the [documentation of the go command](https://golang.org/cmd/go/), get downloads and installs the package.

To prove my theory I tried downloading your package by using only the go get command. It both downloaded and installed the package on my system. Then I was able to start your program using `pmcctv` without calling any forther go command. (I tried it on Gentoo Linux, but I am sure that part of the installation is OS-independent.)

**Comment by laurent22** [comment]
Hello, you're correct, it looks like `go get` will already do the job of installing the package. I'm going to update the readme. Thanks for the information!
